name: release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  micromamba: "1.4.4"
  ghc: "9.2.8"

jobs:
  build-release:
    name: stack w/ ghc ${{ env.ghc }} for ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: ["macos"]
        include:
          # - build: linux
          #   os: ubuntu-latest
          #   target: x86_64-unknown-linux
          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Haskell Stack
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ env.ghc }}
          enable-stack: true
          stack-version: "latest"

      - name: Make ~/.stack as cache
        uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ env.ghc }}-stack

      - name: Build release binary
        run: |
          stack build --copy-bins

      - name: Rename the binary
        run: |
          mv -f "$(stack path --local-bin)/h2o" h2o-${{ matrix.target }}

      - name: Upload the release binary
        uses: actions/upload-artifact@v3
        with:
          name: h2o-${{ matrix.target }}
          path: ./h2o-${{ matrix.target }}
