on: [push]
name: build and test

env:
  micromamba: "1.5.1"
  ghc: "9.8.4"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/provision-with-micromamba@main
        with:
          micromamba-version: ${{ env.micromamba }}
          environment-file: .github/env.yml
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ env.ghc }}
          enable-stack: true
          stack-version: "latest"
      - run: |
          micromamba --version
      - run: |
          gh --version
      - run: |
          stack test 2> /dev/null
