on: [push]
name: build and test

env:
  ghc: "9.8.4"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ env.ghc }}
          enable-stack: true
          stack-version: "latest"
      - name: Install test fixtures
        run: |
          sudo cp test/fixtures/mockcmd /usr/local/bin/
          sudo chmod +x /usr/local/bin/mockcmd
      - run: |
          gh --version
      - run: |
          stack test
